import streamlit as st
import requests
import pandas as pd
import yfinance as yf
from base64 import b64encode
from datetime import datetime, timedelta
import numpy as np
from arch import arch_model

# Lista de empresas
empresas =  [{'Nome de Pregão': '3R PETROLEUM',
  'Ticker': 'RRRP3',
  'CompanyName': '3R PETROLEUM ÓLEO E GÁS S.A'},
 {'Nome de Pregão': '524 PARTICIP',
  'Ticker': 'QVQP3B',
  'CompanyName': '524 PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'AERIS',
  'Ticker': 'AERI3',
  'CompanyName': 'AERIS IND. E COM. DE EQUIP. GERACAO DE ENERGIA S/A'},
 {'Nome de Pregão': 'AES BRASIL',
  'Ticker': 'AESB3',
  'CompanyName': 'AES BRASIL ENERGIA S.A.'},
 {'Nome de Pregão': 'AESOPERACOES',
  'Ticker': 'AESO3',
  'CompanyName': 'AES BRASIL OPERAÇÕES S.A.'},
 {'Nome de Pregão': 'AFLUENTE T',
  'Ticker': 'AFLT3',
  'CompanyName': 'AFLUENTE TRANSMISSÃO DE ENERGIA ELÉTRICA S/A'},
 {'Nome de Pregão': 'AGROGALAXY',
  'Ticker': 'AGXY3',
  'CompanyName': 'AGROGALAXY PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'ALFA HOLDING',
  'Ticker': 'RPAD3',
  'CompanyName': 'ALFA HOLDINGS S.A.'},
 {'Nome de Pregão': 'ALLIAR',
  'Ticker': 'AALR3',
  'CompanyName': 'ALLIANÇA SAÚDE E PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'ALLIED',
  'Ticker': 'ALLD3',
  'CompanyName': 'ALLIED TECNOLOGIA S.A.'},
 {'Nome de Pregão': 'ALLOS', 'Ticker': 'ALOS3', 'CompanyName': 'ALLOS S.A'},
 {'Nome de Pregão': 'ESTAPAR',
  'Ticker': 'ALPK3',
  'CompanyName': 'ALLPARK EMPREENDIMENTOS PARTICIPACOES SERVICOS S.A'},
 {'Nome de Pregão': 'ALPARGATAS',
  'Ticker': 'ALPA3',
  'CompanyName': 'ALPARGATAS S.A.'},
 {'Nome de Pregão': 'ALPER S.A.',
  'Ticker': 'APER3',
  'CompanyName': 'ALPER CONSULTORIA E CORRETORA DE SEGUROS S.A.'},
 {'Nome de Pregão': 'ALPHAVILLE',
  'Ticker': 'AVLL3',
  'CompanyName': 'ALPHAVILLE S.A.'},
 {'Nome de Pregão': 'AMBEV S/A',
  'Ticker': 'ABEV3',
  'CompanyName': 'AMBEV S.A.'},
 {'Nome de Pregão': 'AMBIPAR',
  'Ticker': 'AMBP3',
  'CompanyName': 'AMBIPAR PARTICIPACOES E EMPREENDIMENTOS S/A'},
 {'Nome de Pregão': 'AMERICANAS',
  'Ticker': 'AMER3',
  'CompanyName': 'AMERICANAS S.A'},
 {'Nome de Pregão': 'AMPLA ENERG',
  'Ticker': 'CBEE3',
  'CompanyName': 'AMPLA ENERGIA E SERVICOS S.A.'},
 {'Nome de Pregão': 'ANIMA',
  'Ticker': 'ANIM3',
  'CompanyName': 'ANIMA HOLDING S.A.'},
 {'Nome de Pregão': 'AREZZO CO',
  'Ticker': 'ARZZ3',
  'CompanyName': 'AREZZO INDÚSTRIA E COMÉRCIO S.A.'},
 {'Nome de Pregão': 'ARMAC',
  'Ticker': 'ARML3',
  'CompanyName': 'ARMAC LOCAÇÃO. LOGÍSTICA E SERVIÇOS S.A.'},
 {'Nome de Pregão': 'CARREFOUR BR',
  'Ticker': 'CRFB3',
  'CompanyName': 'ATACADÃO S.A.'},
 {'Nome de Pregão': 'ATMASA',
  'Ticker': 'ATMP3',
  'CompanyName': 'ATMA PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'ATOMPAR',
  'Ticker': 'ATOM3',
  'CompanyName': 'ATOM EMPREENDIMENTOS E PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'KLABIN SA',
  'Ticker': 'KLBN11',
  'CompanyName': 'KLABIN S.A.'},
 {'Nome de Pregão': 'AUREN',
  'Ticker': 'AURE3',
  'CompanyName': 'AUREN ENERGIA S.A.'},
 {'Nome de Pregão': 'AZEVEDO',
  'Ticker': 'AZEV3',
  'CompanyName': 'AZEVEDO E TRAVASSOS S.A.'},
 {'Nome de Pregão': 'AZUL', 'Ticker': 'AZUL4', 'CompanyName': 'AZUL S.A.'},
 {'Nome de Pregão': 'B3',
  'Ticker': 'B3SA3',
  'CompanyName': 'B3 S.A. - BRASIL. BOLSA. BALCÃO'},
 {'Nome de Pregão': 'BAHEMA',
  'Ticker': 'BAHI3',
  'CompanyName': 'BAHEMA EDUCAÇÃO S.A.'},
 {'Nome de Pregão': 'BANCO BMG',
  'Ticker': 'BMGB4',
  'CompanyName': 'BANCO BMG S.A.'},
 {'Nome de Pregão': 'BANESTES',
  'Ticker': 'BEES3',
  'CompanyName': 'BANESTES S.A. - BCO EST ESPIRITO SANTO'},
 {'Nome de Pregão': 'BARDELLA',
  'Ticker': 'BDLL3',
  'CompanyName': 'BARDELLA S.A. INDUSTRIAS MECANICAS'},
 {'Nome de Pregão': 'BAUMER', 'Ticker': 'BALM3', 'CompanyName': 'BAUMER S.A.'},
 {'Nome de Pregão': 'BBSEGURIDADE',
  'Ticker': 'BBSE3',
  'CompanyName': 'BB SEGURIDADE PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'BBMLOGISTICA',
  'Ticker': 'BBM',
  'CompanyName': 'BBM LOGISTICA S.A.'},
 {'Nome de Pregão': 'ABC BRASIL',
  'Ticker': 'ABCB4',
  'CompanyName': 'BCO ABC BRASIL S.A.'},
 {'Nome de Pregão': 'ALFA INVEST',
  'Ticker': 'BRIV3',
  'CompanyName': 'BCO ALFA DE INVESTIMENTO S.A.'},
 {'Nome de Pregão': 'AMAZONIA',
  'Ticker': 'BAZA3',
  'CompanyName': 'BCO AMAZONIA S.A.'},
 {'Nome de Pregão': 'BRADESCO',
  'Ticker': 'BBDC3',
  'CompanyName': 'BCO BRADESCO S.A.'},
 {'Nome de Pregão': 'BRASIL',
  'Ticker': 'BBAS3',
  'CompanyName': 'BCO BRASIL S.A.'},
 {'Nome de Pregão': 'BANESE',
  'Ticker': 'BGIP3',
  'CompanyName': 'BCO ESTADO DE SERGIPE S.A. - BANESE'},
 {'Nome de Pregão': 'BANPARA',
  'Ticker': 'BPAR3',
  'CompanyName': 'BCO ESTADO DO PARA S.A.'},
 {'Nome de Pregão': 'BANRISUL',
  'Ticker': 'BRSR3',
  'CompanyName': 'BCO ESTADO DO RIO GRANDE DO SUL S.A.'},
 {'Nome de Pregão': 'MERC INVEST',
  'Ticker': 'BMIN3',
  'CompanyName': 'BCO MERCANTIL DE INVESTIMENTOS S.A.'},
 {'Nome de Pregão': 'MERCANTIL',
  'Ticker': 'BMEB3',
  'CompanyName': 'BCO MERCANTIL DO BRASIL S.A.'},
 {'Nome de Pregão': 'NORD BRASIL',
  'Ticker': 'BNBR3',
  'CompanyName': 'BCO NORDESTE DO BRASIL S.A.'},
 {'Nome de Pregão': 'BANCO PAN',
  'Ticker': 'BPAN4',
  'CompanyName': 'BCO PAN S.A.'},
 {'Nome de Pregão': 'PINE', 'Ticker': 'PINE3', 'CompanyName': 'BCO PINE S.A.'},
 {'Nome de Pregão': 'BEMOBI TECH',
  'Ticker': 'BMOB3',
  'CompanyName': 'BEMOBI MOBILE TECH S.A.'},
 {'Nome de Pregão': 'BETAPART',
  'Ticker': 'BETP3B',
  'CompanyName': 'BETAPART PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'BIC MONARK',
  'Ticker': 'BMKS3',
  'CompanyName': 'BICICLETAS MONARK S.A.'},
 {'Nome de Pregão': 'BIOMM', 'Ticker': 'BIOM3', 'CompanyName': 'BIOMM S.A.'},
 {'Nome de Pregão': 'BLAU',
  'Ticker': 'BLAU3',
  'CompanyName': 'BLAU FARMACÊUTICA S.A.'},
 {'Nome de Pregão': 'BOA SAFRA',
  'Ticker': 'SOJA3',
  'CompanyName': 'BOA SAFRA SEMENTES S.A.'},
 {'Nome de Pregão': 'BOMBRIL',
  'Ticker': 'BOBR3',
  'CompanyName': 'BOMBRIL S.A.'},
 {'Nome de Pregão': 'VIPAL',
  'Ticker': 0,
  'CompanyName': 'BORRACHAS VIPAL S.A.'},
 {'Nome de Pregão': 'BR MALLS PAR',
  'Ticker': 'BRML3',
  'CompanyName': 'BR MALLS PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'BRADESPAR',
  'Ticker': 'BRAP3',
  'CompanyName': 'BRADESPAR S.A.'},
 {'Nome de Pregão': 'BRASILAGRO',
  'Ticker': 'AGRO3',
  'CompanyName': 'BRASILAGRO - CIA BRAS DE PROP AGRICOLAS'},
 {'Nome de Pregão': 'BRASKEM',
  'Ticker': 'BRKM3',
  'CompanyName': 'BRASKEM S.A.'},
 {'Nome de Pregão': 'BRB BANCO',
  'Ticker': 'BSLI3',
  'CompanyName': 'BRB BCO DE BRASILIA S.A.'},
 {'Nome de Pregão': 'BRF SA', 'Ticker': 'BRFS3', 'CompanyName': 'BRF S.A.'},
 {'Nome de Pregão': 'BRISANET',
  'Ticker': 'BRIT3',
  'CompanyName': 'BRISANET PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'BRQ',
  'Ticker': 'BRQB',
  'CompanyName': 'BRQ SOLUCOES EM INFORMATICA S.A.'},
 {'Nome de Pregão': 'CABINDA PART',
  'Ticker': 0,
  'CompanyName': 'CABINDA PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'CAIXA SEGURI',
  'Ticker': 'CXSE3',
  'CompanyName': 'CAIXA SEGURIDADE PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'CAMBUCI',
  'Ticker': 'CAMB3',
  'CompanyName': 'CAMBUCI S.A.'},
 {'Nome de Pregão': 'CAMIL',
  'Ticker': 'CAML3',
  'CompanyName': 'CAMIL ALIMENTOS S.A.'},
 {'Nome de Pregão': 'CCR SA', 'Ticker': 'CCRO3', 'CompanyName': 'CCR S.A.'},
 {'Nome de Pregão': 'CEA MODAS',
  'Ticker': 'CEAB3',
  'CompanyName': 'CEA MODAS S.A.'},
 {'Nome de Pregão': 'CEMEPE',
  'Ticker': 713854,
  'CompanyName': 'CEMEPE INVESTIMENTOS S.A.'},
 {'Nome de Pregão': 'ELETROBRAS',
  'Ticker': 'ELET3',
  'CompanyName': 'CENTRAIS ELET BRAS S.A. - ELETROBRAS'},
 {'Nome de Pregão': 'CELESC',
  'Ticker': 'CLSC3',
  'CompanyName': 'CENTRAIS ELET DE SANTA CATARINA S.A.'},
 {'Nome de Pregão': 'P.ACUCAR-CBD',
  'Ticker': 'PCAR3',
  'CompanyName': 'CIA BRASILEIRA DE DISTRIBUICAO'},
 {'Nome de Pregão': 'CASAN',
  'Ticker': 'CASN3',
  'CompanyName': 'CIA CATARINENSE DE AGUAS E SANEAM.-CASAN'},
 {'Nome de Pregão': 'CELGPAR',
  'Ticker': 'GPAR3',
  'CompanyName': 'CIA CELG DE PARTICIPACOES - CELGPAR'},
 {'Nome de Pregão': 'CEG',
  'Ticker': 'CEGR3',
  'CompanyName': 'CIA DISTRIB DE GAS DO RIO DE JANEIRO-CEG'},
 {'Nome de Pregão': 'COELBA',
  'Ticker': 'CEEB3',
  'CompanyName': 'CIA ELETRICIDADE EST. DA BAHIA - COELBA'},
 {'Nome de Pregão': 'CEB',
  'Ticker': 'CEBR3',
  'CompanyName': 'CIA ENERGETICA DE BRASILIA'},
 {'Nome de Pregão': 'CEMIG',
  'Ticker': 'CMIG3',
  'CompanyName': 'CIA ENERGETICA DE MINAS GERAIS - CEMIG'},
 {'Nome de Pregão': 'COELCE',
  'Ticker': 'COCE3',
  'CompanyName': 'CIA ENERGETICA DO CEARA - COELCE'},
 {'Nome de Pregão': 'COSERN',
  'Ticker': 'CSRN3',
  'CompanyName': 'CIA ENERGETICA DO RIO GDE NORTE - COSERN'},
 {'Nome de Pregão': 'CEEE-D',
  'Ticker': 'CEED3',
  'CompanyName': 'CIA ESTADUAL DE DISTRIB ENER ELET-CEEE-D'},
 {'Nome de Pregão': 'CEEE-G',
  'Ticker': 'CGEE3',
  'CompanyName': 'CIA ESTADUAL DE GERAÇÃO DE ENERGIA ELÉTRICA-CEEE-G'},
 {'Nome de Pregão': 'FERBASA',
  'Ticker': 'FESA3',
  'CompanyName': 'CIA FERRO LIGAS DA BAHIA - FERBASA'},
 {'Nome de Pregão': 'CEDRO',
  'Ticker': 'CEDO3',
  'CompanyName': 'CIA FIACAO TECIDOS CEDRO CACHOEIRA'},
 {'Nome de Pregão': 'COMGAS',
  'Ticker': 'CGAS3',
  'CompanyName': 'CIA GAS DE SAO PAULO - COMGAS'},
 {'Nome de Pregão': 'HABITASUL',
  'Ticker': 'HBTS5',
  'CompanyName': 'CIA HABITASUL DE PARTICIPACOES'},
 {'Nome de Pregão': 'CHESF',
  'Ticker': 0,
  'CompanyName': 'CIA HIDRO ELETRICA DO SAO FRANCISCO - CHESF'},
 {'Nome de Pregão': 'IND CATAGUAS',
  'Ticker': 'CATA3',
  'CompanyName': 'CIA INDUSTRIAL CATAGUASES'},
 {'Nome de Pregão': 'LOCAMERICA',
  'Ticker': 'LCAM3',
  'CompanyName': 'CIA LOCAÇÃO DAS AMÉRICAS'},
 {'Nome de Pregão': 'MELHOR SP',
  'Ticker': 0,
  'CompanyName': 'CIA MELHORAMENTOS DE SAO PAULO'},
 {'Nome de Pregão': 'COPEL',
  'Ticker': 'CPLE3',
  'CompanyName': 'CIA PARANAENSE DE ENERGIA - COPEL'},
 {'Nome de Pregão': 'PAR AL BAHIA',
  'Ticker': 'PEAB3',
  'CompanyName': 'CIA PARTICIPACOES ALIANCA DA BAHIA'},
 {'Nome de Pregão': 'SABESP',
  'Ticker': 'SBSP3',
  'CompanyName': 'CIA SANEAMENTO BASICO EST SAO PAULO'},
 {'Nome de Pregão': 'COPASA',
  'Ticker': 'CSMG3',
  'CompanyName': 'CIA SANEAMENTO DE MINAS GERAIS-COPASA MG'},
 {'Nome de Pregão': 'SANEPAR',
  'Ticker': 'SAPR3',
  'CompanyName': 'CIA SANEAMENTO DO PARANA - SANEPAR'},
 {'Nome de Pregão': 'SID NACIONAL',
  'Ticker': 'CSNA3',
  'CompanyName': 'CIA SIDERURGICA NACIONAL'},
 {'Nome de Pregão': 'COTEMINAS',
  'Ticker': 'CTNM3',
  'CompanyName': 'CIA TECIDOS NORTE DE MINAS COTEMINAS'},
 {'Nome de Pregão': 'SANTANENSE',
  'Ticker': 'CTSA3',
  'CompanyName': 'CIA TECIDOS SANTANENSE'},
 {'Nome de Pregão': 'CIELO',
  'Ticker': 'CIEL3',
  'CompanyName': 'CIELO S.A. - INSTITUIÇÃO DE PAGAMENTO'},
 {'Nome de Pregão': 'CIMS', 'Ticker': 'CMFA3', 'CompanyName': 'CIMS S.A.'},
 {'Nome de Pregão': 'CLEARSALE',
  'Ticker': 'CLSA3',
  'CompanyName': 'CLEAR SALE S.A.'},
 {'Nome de Pregão': 'VIVEO',
  'Ticker': 'VVEO3',
  'CompanyName': 'CM HOSPITALAR S.A.'},
 {'Nome de Pregão': 'COGNA ON',
  'Ticker': 'COGN3',
  'CompanyName': 'COGNA EDUCAÇÃO S.A.'},
 {'Nome de Pregão': 'COMERC PAR',
  'Ticker': 0,
  'CompanyName': 'COMERC ENERGIA S.A.'},
 {'Nome de Pregão': 'CBA',
  'Ticker': 'CBAV3',
  'CompanyName': 'COMPANHIA BRASILEIRA DE ALUMÍNIO'},
 {'Nome de Pregão': 'COMPASS',
  'Ticker': 'PASS3',
  'CompanyName': 'COMPASS GAS E ENERGIA S.A.'},
 {'Nome de Pregão': 'ODERICH',
  'Ticker': 'ODER3',
  'CompanyName': 'CONSERVAS ODERICH S.A.'},
 {'Nome de Pregão': 'ALFA CONSORC',
  'Ticker': 'BRGE3',
  'CompanyName': 'CONSORCIO ALFA DE ADMINISTRACAO S.A.'},
 {'Nome de Pregão': 'CONST A LIND',
  'Ticker': 'CALI3',
  'CompanyName': 'CONSTRUTORA ADOLPHO LINDENBERG S.A.'},
 {'Nome de Pregão': 'TENDA',
  'Ticker': 'TEND3',
  'CompanyName': 'CONSTRUTORA TENDA S.A.'},
 {'Nome de Pregão': 'COSAN', 'Ticker': 'CSAN3', 'CompanyName': 'COSAN S.A.'},
 {'Nome de Pregão': 'CPFL ENERGIA',
  'Ticker': 'CPFE3',
  'CompanyName': 'CPFL ENERGIA S.A.'},
 {'Nome de Pregão': 'MERC FINANC',
  'Ticker': 'MERC3',
  'CompanyName': 'MERCANTIL FINANCEIRA S.A. \x96 CRED. FINANC. E INVEST'},
 {'Nome de Pregão': 'CRUZEIRO EDU',
  'Ticker': 'CSED3',
  'CompanyName': 'CRUZEIRO DO SUL EDUCACIONAL S.A.'},
 {'Nome de Pregão': 'CSNMINERACAO',
  'Ticker': 25585,
  'CompanyName': 'CSN MINERAÇÃO S.A.'},
 {'Nome de Pregão': 'CSU DIGITAL',
  'Ticker': 'CSUD3',
  'CompanyName': 'CSU DIGITAL S.A.'},
 {'Nome de Pregão': 'CTC S.A.',
  'Ticker': 'CTCA3',
  'CompanyName': 'CTC - CENTRO DE TECNOLOGIA CANAVIEIRA S.A.'},
 {'Nome de Pregão': 'TRAN PAULIST',
  'Ticker': 'TRPL3',
  'CompanyName': 'CTEEP - CIA TRANSMISSÃO ENERGIA ELÉTRICA PAULISTA'},
 {'Nome de Pregão': 'CURY S/A',
  'Ticker': 'CURY3',
  'CompanyName': 'CURY CONSTRUTORA E INCORPORADORA S.A.'},
 {'Nome de Pregão': 'CVC BRASIL',
  'Ticker': 'CVCB3',
  'CompanyName': 'CVC BRASIL OPERADORA E AGÊNCIA DE VIAGENS S.A.'},
 {'Nome de Pregão': 'CYRELA REALT',
  'Ticker': 'CYRE3',
  'CompanyName': 'CYRELA BRAZIL REALTY S.A.EMPREEND E PART'},
 {'Nome de Pregão': 'D1000VFARMA',
  'Ticker': 'DMVF3',
  'CompanyName': 'D1000 VAREJO FARMA PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'DESKTOP',
  'Ticker': 'DESK3',
  'CompanyName': 'DESKTOP S.A.'},
 {'Nome de Pregão': 'DEXCO', 'Ticker': 'DXCO3', 'CompanyName': 'DEXCO S.A.'},
 {'Nome de Pregão': 'DEXXOS PAR',
  'Ticker': 'DEXP3',
  'CompanyName': 'DEXXOS PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'DASA',
  'Ticker': 'DASA3',
  'CompanyName': 'DIAGNOSTICOS DA AMERICA S.A.'},
 {'Nome de Pregão': 'DIMED',
  'Ticker': 'PNVL3',
  'CompanyName': 'DIMED S.A. DISTRIBUIDORA DE MEDICAMENTOS'},
 {'Nome de Pregão': 'DIRECIONAL',
  'Ticker': 'DIRR3',
  'CompanyName': 'DIRECIONAL ENGENHARIA S.A.'},
 {'Nome de Pregão': 'DMFINANCEIRA',
  'Ticker': 'DMFN3',
  'CompanyName': 'DM FINANCEIRA S.A. - CRÉDITO. FINANC E INVEST'},
 {'Nome de Pregão': 'DOHLER', 'Ticker': 'DOHL3', 'CompanyName': 'DOHLER S.A.'},
 {'Nome de Pregão': 'DOTZ SA', 'Ticker': 'DOTZ3', 'CompanyName': 'DOTZ S.A.'},
 {'Nome de Pregão': 'DTCOM-DIRECT',
  'Ticker': 'DTCY3',
  'CompanyName': 'DTCOM - DIRECT TO COMPANY S.A.'},
 {'Nome de Pregão': 'ECORODOVIAS',
  'Ticker': 'ECOR3',
  'CompanyName': 'ECORODOVIAS INFRAESTRUTURA E LOGÍSTICA S.A.'},
 {'Nome de Pregão': 'ACO ALTONA',
  'Ticker': 'EALT3',
  'CompanyName': 'ELECTRO ACO ALTONA S.A.'},
 {'Nome de Pregão': 'ELEKTRO',
  'Ticker': 'EKTR3',
  'CompanyName': 'ELEKTRO REDES S.A.'},
 {'Nome de Pregão': 'ELETROPAR',
  'Ticker': 'LIPR3',
  'CompanyName': 'ELETROBRÁS PARTICIPAÇÕES S.A. - ELETROPAR'},
 {'Nome de Pregão': 'ELETROMIDIA',
  'Ticker': 'ELMD3',
  'CompanyName': 'ELETROMIDIA S.A.'},
 {'Nome de Pregão': 'EMAE',
  'Ticker': 'EMAE3',
  'CompanyName': 'EMAE - EMPRESA METROP.AGUAS ENERGIA S.A.'},
 {'Nome de Pregão': 'EMBPAR S/A',
  'Ticker': '1545-8',
  'CompanyName': 'EMBPAR PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'EMBRAER',
  'Ticker': 'EMBR3',
  'CompanyName': 'EMBRAER S.A.'},
 {'Nome de Pregão': 'PAGUE MENOS',
  'Ticker': 'PGMN3',
  'CompanyName': 'EMPREENDIMENTOS PAGUE MENOS S.A.'},
 {'Nome de Pregão': 'ENAUTA PART',
  'Ticker': 'ENAT3',
  'CompanyName': 'ENAUTA PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'ENERGISA MT',
  'Ticker': 'ENMT3',
  'CompanyName': 'ENERGISA MATO GROSSO-DISTRIBUIDORA DE ENERGIA S/A'},
 {'Nome de Pregão': 'ENERGISA',
  'Ticker': 'ENGI3',
  'CompanyName': 'ENERGISA S.A.'},
 {'Nome de Pregão': 'ENEVA', 'Ticker': 'ENEV3', 'CompanyName': 'ENEVA S.A'},
 {'Nome de Pregão': 'ENGIE BRASIL',
  'Ticker': 'EGIE3',
  'CompanyName': 'ENGIE BRASIL ENERGIA S.A.'},
 {'Nome de Pregão': 'ENJOEI', 'Ticker': 'ENJU3', 'CompanyName': 'ENJOEI S.A.'},
 {'Nome de Pregão': 'ENVIRONMENT',
  'Ticker': 0,
  'CompanyName': 'ENVIRONMENTAL ESG PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'EQUATORIAL',
  'Ticker': 'EQTL3',
  'CompanyName': 'EQUATORIAL ENERGIA S.A.'},
 {'Nome de Pregão': 'EQTLMARANHAO',
  'Ticker': 'ENMA3B',
  'CompanyName': 'EQUATORIAL MARANHÃO DISTRIBUIDORA DE ENERGIA S.A.'},
 {'Nome de Pregão': 'EQTL PARA',
  'Ticker': 'CELP3',
  'CompanyName': 'EQUATORIAL PARA DISTRIBUIDORA DE ENERGIA S.A.'},
 {'Nome de Pregão': 'ETERNIT',
  'Ticker': 'ETER3',
  'CompanyName': 'ETERNIT S.A.'},
 {'Nome de Pregão': 'EUCATEX',
  'Ticker': 'EUCA3',
  'CompanyName': 'EUCATEX S.A. INDUSTRIA E COMERCIO'},
 {'Nome de Pregão': 'EUROFARMA SA',
  'Ticker': 'EUFA',
  'CompanyName': 'EUROFARMA LABORATORIOS S.A'},
 {'Nome de Pregão': 'EVEN',
  'Ticker': 'EVEN3',
  'CompanyName': 'EVEN CONSTRUTORA E INCORPORADORA S.A.'},
 {'Nome de Pregão': 'EXCELSIOR',
  'Ticker': 'BAUH3',
  'CompanyName': 'EXCELSIOR ALIMENTOS S.A.'},
 {'Nome de Pregão': 'EZTEC',
  'Ticker': 'EZTC3',
  'CompanyName': 'EZ TEC EMPREEND. E PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'NISSEI FARMA',
  'Ticker': 0,
  'CompanyName': 'FARMÁCIA E DROGARIA NISSEI S.A.'},
 {'Nome de Pregão': 'FER C ATLANT',
  'Ticker': 'VSPT3',
  'CompanyName': 'FERROVIA CENTRO-ATLANTICA S.A.'},
 {'Nome de Pregão': 'FER HERINGER',
  'Ticker': 'FHER3',
  'CompanyName': 'FERTILIZANTES HERINGER S.A.'},
 {'Nome de Pregão': 'FICA',
  'Ticker': 'CRDE3',
  'CompanyName': 'FICA EMPREENDIMENTOS IMOBILIÁRIOS S.A'},
 {'Nome de Pregão': 'ALFA FINANC',
  'Ticker': 'CRIV3',
  'CompanyName': 'FINANCEIRA ALFA S.A.- CRED FINANC E INVS'},
 {'Nome de Pregão': 'FLEURY', 'Ticker': 'FLRY3', 'CompanyName': 'FLEURY S.A.'},
 {'Nome de Pregão': 'FRAS-LE',
  'Ticker': 'FRAS3',
  'CompanyName': 'FRAS-LE S.A.'},
 {'Nome de Pregão': 'GAFISA', 'Ticker': 'GFSA3', 'CompanyName': 'GAFISA S.A.'},
 {'Nome de Pregão': 'GAMA PART',
  'Ticker': 'OPGM3B',
  'CompanyName': 'GAMA PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'GENERALSHOPP',
  'Ticker': 'GSHP3',
  'CompanyName': 'GENERAL SHOPPING E OUTLETS DO BRASIL S.A.'},
 {'Nome de Pregão': 'GERDAU', 'Ticker': 'GGBR3', 'CompanyName': 'GERDAU S.A.'},
 {'Nome de Pregão': 'GETNINJAS',
  'Ticker': 'NINJ3',
  'CompanyName': 'GETNINJAS S.A.'},
 {'Nome de Pregão': 'GOL',
  'Ticker': 'GOLL4',
  'CompanyName': 'GOL LINHAS AEREAS INTELIGENTES S.A.'},
 {'Nome de Pregão': 'GPS',
  'Ticker': 'GGPS3',
  'CompanyName': 'GPS PARTICIPACOES E EMPREENDIMENTOS S.A.'},
 {'Nome de Pregão': 'GRAZZIOTIN',
  'Ticker': 'CGRA3',
  'CompanyName': 'GRAZZIOTIN S.A.'},
 {'Nome de Pregão': 'GRENDENE',
  'Ticker': 'GRND3',
  'CompanyName': 'GRENDENE S.A.'},
 {'Nome de Pregão': 'CASAS BAHIA',
  'Ticker': 'BHIA3',
  'CompanyName': 'GRUPO CASAS BAHIA S.A.'},
 {'Nome de Pregão': 'GRUPO SOMA',
  'Ticker': 'SOMA3',
  'CompanyName': 'GRUPO DE MODA SOMA S.A.'},
 {'Nome de Pregão': 'GRUPO MATEUS',
  'Ticker': 'GMAT3',
  'CompanyName': 'GRUPO MATEUS S.A.'},
 {'Nome de Pregão': 'GRUPO SBF',
  'Ticker': 'SBFG3',
  'CompanyName': 'GRUPO SBF SA'},
 {'Nome de Pregão': 'GUARARAPES',
  'Ticker': 'GUAR3',
  'CompanyName': 'GUARARAPES CONFECCOES S.A.'},
 {'Nome de Pregão': 'HAGA S/A',
  'Ticker': 2,
  'CompanyName': 'HAGA S.A. INDUSTRIA E COMERCIO'},
 {'Nome de Pregão': 'HAPVIDA',
  'Ticker': 'HAPV3',
  'CompanyName': 'HAPVIDA PARTICIPACOES E INVESTIMENTOS SA'},
 {'Nome de Pregão': 'HBR REALTY',
  'Ticker': 'HBRE3',
  'CompanyName': 'HBR REALTY EMPREENDIMENTOS IMOBILIARIOS S/A'},
 {'Nome de Pregão': 'HELBOR',
  'Ticker': 'HBOR3',
  'CompanyName': 'HELBOR EMPREENDIMENTOS S.A.'},
 {'Nome de Pregão': 'HERCULES',
  'Ticker': 'HETA3',
  'CompanyName': 'HERCULES S.A. FABRICA DE TALHERES'},
 {'Nome de Pregão': 'HIDROVIAS',
  'Ticker': 'HBSA3',
  'CompanyName': 'HIDROVIAS DO BRASIL S.A.'},
 {'Nome de Pregão': 'HMOBI S.A',
  'Ticker': 'HMOB3',
  'CompanyName': 'HMOBI PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'HOSPITALCARE',
  'Ticker': 0,
  'CompanyName': 'HOSPITAL CARE CALEDONIA S.A.'},
 {'Nome de Pregão': 'MATER DEI',
  'Ticker': 'MATD3',
  'CompanyName': 'HOSPITAL MATER DEI S/A'},
 {'Nome de Pregão': 'HOTEIS OTHON',
  'Ticker': 'HOOT4',
  'CompanyName': 'HOTEIS OTHON S.A.'},
 {'Nome de Pregão': 'AGRIBRASIL',
  'Ticker': 'GRAO3',
  'CompanyName': 'HUMBERG AGRIBRASIL COM. E EXPORT. DE GRÃOS S.A.'},
 {'Nome de Pregão': 'HYPERA', 'Ticker': 'HYPE3', 'CompanyName': 'HYPERA S.A.'},
 {'Nome de Pregão': 'IGUA SA',
  'Ticker': 'IGSN3',
  'CompanyName': 'IGUA SANEAMENTO S.A.'},
 {'Nome de Pregão': 'IGUATEMI',
  'Ticker': 'IGTA3',
  'CompanyName': 'IGUATEMI EMPRESA DE SHOPPING CENTERS S.A'},
 {'Nome de Pregão': 'IGUATEMI S.A',
  'Ticker': 'IGTI3',
  'CompanyName': 'IGUATEMI S.A.'},
 {'Nome de Pregão': 'INC SA',
  'Ticker': 'INNT3',
  'CompanyName': 'INC EMPREENDIMENTOS IMOBILIÁRIOS S.A.'},
 {'Nome de Pregão': 'INEPAR',
  'Ticker': 'INEP3',
  'CompanyName': 'INEPAR S.A. INDUSTRIA E CONSTRUCOES'},
 {'Nome de Pregão': 'INFRACOMM',
  'Ticker': 'IFCM3',
  'CompanyName': 'INFRACOMMERCE CXAAS S.A.'},
 {'Nome de Pregão': 'INTELBRAS',
  'Ticker': 'INTB3',
  'CompanyName': 'INTELBRAS S.A. IND DE TELEC ELETRONICA BRASILEIRA'},
 {'Nome de Pregão': 'IMC S/A',
  'Ticker': 'MEAL3',
  'CompanyName': 'INTERNATIONAL MEAL COMPANY ALIMENTACAO S.A.'},
 {'Nome de Pregão': 'INVEST BEMGE',
  'Ticker': 'FIGE3',
  'CompanyName': 'INVESTIMENTOS BEMGE S.A.'},
 {'Nome de Pregão': 'INVEPAR',
  'Ticker': 'IVPR3',
  'CompanyName': 'INVESTIMENTOS E PARTICIP. EM INFRA S.A. - INVEPAR'},
 {'Nome de Pregão': 'IOCHP-MAXION',
  'Ticker': 'MYPK3',
  'CompanyName': 'IOCHPE MAXION S.A.'},
 {'Nome de Pregão': 'IRANI',
  'Ticker': 'RANI3',
  'CompanyName': 'IRANI PAPEL E EMBALAGEM S.A.'},
 {'Nome de Pregão': 'IRBBRASIL RE',
  'Ticker': 'IRBR3',
  'CompanyName': 'IRB - BRASIL RESSEGUROS S.A.'},
 {'Nome de Pregão': 'ITAUUNIBANCO',
  'Ticker': 'ITUB3',
  'CompanyName': 'ITAU UNIBANCO HOLDING S.A.'},
 {'Nome de Pregão': 'ITAUSA', 'Ticker': 'ITSA3', 'CompanyName': 'ITAUSA S.A.'},
 {'Nome de Pregão': 'JALLESMACHAD',
  'Ticker': 'JALL3',
  'CompanyName': 'JALLES MACHADO S.A.'},
 {'Nome de Pregão': 'JBS', 'Ticker': 'JBSS3', 'CompanyName': 'JBS S.A.'},
 {'Nome de Pregão': 'JHSF PART',
  'Ticker': 'JHSF3',
  'CompanyName': 'JHSF PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'JOAO FORTES',
  'Ticker': 'JFEN3',
  'CompanyName': 'JOAO FORTES ENGENHARIA S.A.'},
 {'Nome de Pregão': 'JOSAPAR',
  'Ticker': 'JOPA3',
  'CompanyName': 'JOSAPAR-JOAQUIM OLIVEIRA S.A. - PARTICIP'},
 {'Nome de Pregão': 'JSL', 'Ticker': 'JSLG3', 'CompanyName': 'JSL S.A.'},
 {'Nome de Pregão': 'KALLAS',
  'Ticker': 'KLAS3',
  'CompanyName': 'KALLAS INCORPORACOES E CONSTRUCOES S.A.'},
 {'Nome de Pregão': 'KARSTEN',
  'Ticker': 'CTKA3',
  'CompanyName': 'KARSTEN S.A.'},
 {'Nome de Pregão': 'KEPLER WEBER',
  'Ticker': 'KEPL3',
  'CompanyName': 'KEPLER WEBER S.A.'},
 {'Nome de Pregão': 'KORA SAUDE',
  'Ticker': 'KRSA3',
  'CompanyName': 'KORA SAÚDE PARTICIPAÇÕES S.A'},
 {'Nome de Pregão': 'LAVVI',
  'Ticker': 'LAVV3',
  'CompanyName': 'LAVVI EMPREENDIMENTOS IMOBILIÁRIOS S.A.'},
 {'Nome de Pregão': 'LIFEMED',
  'Ticker': 'LMED',
  'CompanyName': 'LIFEMED INDUSTRIAL EQUIP. DE ART. MÉD. HOSP. S.A.'},
 {'Nome de Pregão': 'LIGHT S/A',
  'Ticker': 'LIGT3',
  'CompanyName': 'LIGHT S.A.'},
 {'Nome de Pregão': 'LITEL',
  'Ticker': 'LTEL3B',
  'CompanyName': 'LITEL PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'LITELA',
  'Ticker': 'LTLA',
  'CompanyName': 'LITELA PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'LOCALIZA',
  'Ticker': 'RENT3',
  'CompanyName': 'LOCALIZA RENT A CAR S.A.'},
 {'Nome de Pregão': 'LWSA',
  'Ticker': 'LWSA3',
  'CompanyName': 'LOCAWEB SERVIÇOS DE INTERNET S.A.'},
 {'Nome de Pregão': 'LOG COM PROP',
  'Ticker': 'LOGG3',
  'CompanyName': 'LOG COMMERCIAL PROPERTIES'},
 {'Nome de Pregão': 'LOG-IN',
  'Ticker': 'LOGN3',
  'CompanyName': 'LOG-IN LOGISTICA INTERMODAL S.A.'},
 {'Nome de Pregão': 'QUERO-QUERO',
  'Ticker': 'LJQQ3',
  'CompanyName': 'LOJAS QUERO-QUERO S/A'},
 {'Nome de Pregão': 'LOJAS RENNER',
  'Ticker': 'LREN3',
  'CompanyName': 'LOJAS RENNER S.A.'},
 {'Nome de Pregão': 'LOPES BRASIL',
  'Ticker': 'LPSB3',
  'CompanyName': 'LPS BRASIL - CONSULTORIA DE IMOVEIS S.A.'},
 {'Nome de Pregão': 'LUPATECH',
  'Ticker': 'LUPA3',
  'CompanyName': 'LUPATECH S.A.'},
 {'Nome de Pregão': 'M.DIASBRANCO',
  'Ticker': 'MDIA3',
  'CompanyName': 'M.DIAS BRANCO S.A. IND COM DE ALIMENTOS'},
 {'Nome de Pregão': 'MAESTROLOC',
  'Ticker': 'MSRO3',
  'CompanyName': 'MAESTRO LOCADORA DE VEICULOS S.A.'},
 {'Nome de Pregão': 'MAGAZ LUIZA',
  'Ticker': 'MGLU3',
  'CompanyName': 'MAGAZINE LUIZA S.A.'},
 {'Nome de Pregão': 'METAL LEVE',
  'Ticker': 'LEVE3',
  'CompanyName': 'MAHLE-METAL LEVE S.A.'},
 {'Nome de Pregão': 'MANGELS INDL',
  'Ticker': 'MGEL3',
  'CompanyName': 'MANGELS INDUSTRIAL S.A.'},
 {'Nome de Pregão': 'ESTRELA',
  'Ticker': 'ESTR4',
  'CompanyName': 'MANUFATURA DE BRINQUEDOS ESTRELA S.A.'},
 {'Nome de Pregão': 'MARCOPOLO',
  'Ticker': 'POMO3',
  'CompanyName': 'MARCOPOLO S.A.'},
 {'Nome de Pregão': 'MARFRIG',
  'Ticker': 'ADR',
  'CompanyName': 'MARFRIG GLOBAL FOODS S.A.'},
 {'Nome de Pregão': 'LOJAS MARISA',
  'Ticker': 'AMAR3',
  'CompanyName': 'MARISA LOJAS S.A.'},
 {'Nome de Pregão': 'MELIUZ', 'Ticker': 'CASH3', 'CompanyName': 'MÉLIUZ S.A.'},
 {'Nome de Pregão': 'MELNICK',
  'Ticker': 'MELK3',
  'CompanyName': 'MELNICK DESENVOLVIMENTO IMOBILIÁRIO S.A.'},
 {'Nome de Pregão': 'METALFRIO',
  'Ticker': 'FRIO3',
  'CompanyName': 'METALFRIO SOLUTIONS S.A.'},
 {'Nome de Pregão': 'GERDAU MET',
  'Ticker': 'GOAU3',
  'CompanyName': 'METALURGICA GERDAU S.A.'},
 {'Nome de Pregão': 'RIOSULENSE',
  'Ticker': 'RSUL3',
  'CompanyName': 'METALURGICA RIOSULENSE S.A.'},
 {'Nome de Pregão': 'METISA',
  'Ticker': 'MTSA3',
  'CompanyName': 'METISA METALURGICA TIMBOENSE S.A.'},
 {'Nome de Pregão': 'MILLS',
  'Ticker': 'MILS3',
  'CompanyName': 'MILLS LOCAÇÃO. SERVIÇOS E LOGÍSTICA S.A'},
 {'Nome de Pregão': 'MINASMAQUINA',
  'Ticker': 'MMAQ3',
  'CompanyName': 'MINASMAQUINAS S.A.'},
 {'Nome de Pregão': 'MINERVA',
  'Ticker': 'BEEF3',
  'CompanyName': 'MINERVA S.A.'},
 {'Nome de Pregão': 'MINUPAR',
  'Ticker': 'MNPR3',
  'CompanyName': 'MINUPAR PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'MITRE REALTY',
  'Ticker': 'MTRE3',
  'CompanyName': 'MITRE REALTY EMPREENDIMENTOS E PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'MOBLY', 'Ticker': 'MBLY3', 'CompanyName': 'MOBLY S.A.'},
 {'Nome de Pregão': 'MONT ARANHA',
  'Ticker': 'MOAR3',
  'CompanyName': 'MONTEIRO ARANHA S.A.'},
 {'Nome de Pregão': 'MOURA DUBEUX',
  'Ticker': 'MDNE3',
  'CompanyName': 'MOURA DUBEUX ENGENHARIA S/A'},
 {'Nome de Pregão': 'MOVIDA',
  'Ticker': 'MOVI3',
  'CompanyName': 'MOVIDA PARTICIPACOES SA'},
 {'Nome de Pregão': 'ESPACOLASER',
  'Ticker': 'ESPA3',
  'CompanyName': 'MPM CORPÓREOS S.A.'},
 {'Nome de Pregão': 'MRS LOGIST',
  'Ticker': 'MRSA3',
  'CompanyName': 'MRS LOGISTICA S.A.'},
 {'Nome de Pregão': 'MRV',
  'Ticker': 'MRVE3',
  'CompanyName': 'MRV ENGENHARIA E PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'MULTILASER',
  'Ticker': 'MLAS3',
  'CompanyName': 'GRUPO MULTI S.A.'},
 {'Nome de Pregão': 'MULTIPLAN',
  'Ticker': 'MULT3',
  'CompanyName': 'MULTIPLAN - EMPREEND IMOBILIARIOS S.A.'},
 {'Nome de Pregão': 'MUNDIAL',
  'Ticker': 'MNDL3',
  'CompanyName': 'MUNDIAL S.A. - PRODUTOS DE CONSUMO'},
 {'Nome de Pregão': 'GRUPO NATURA',
  'Ticker': 'NTCO3',
  'CompanyName': 'NATURA &CO HOLDING S.A.'},
 {'Nome de Pregão': 'NEOENERGIA',
  'Ticker': 'NEOE3',
  'CompanyName': 'NEOENERGIA VALE DO ITAJAÍ TRANSMISSÃO DE ENERGIA'},
 {'Nome de Pregão': 'NEOGRID',
  'Ticker': 'NGRD3',
  'CompanyName': 'NEOGRID PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'NEXPE',
  'Ticker': 'NEXP3',
  'CompanyName': 'NEXPE PARTICIPAÇÕES S.A'},
 {'Nome de Pregão': 'NORDON MET',
  'Ticker': 1,
  'CompanyName': 'NORDON INDUSTRIAS METALURGICAS S.A.'},
 {'Nome de Pregão': 'NORTCQUIMICA',
  'Ticker': 'NRTQ3',
  'CompanyName': 'NORTEC QUÍMICA S.A.'},
 {'Nome de Pregão': 'NUTRIPLANT',
  'Ticker': 'NUTR3',
  'CompanyName': 'NUTRIPLANT INDUSTRIA E COMERCIO S.A.'},
 {'Nome de Pregão': 'OCEANPACT',
  'Ticker': 'OPCT3',
  'CompanyName': 'OCEANPACT SERVICOS MARITIMOS S.A.'},
 {'Nome de Pregão': 'ODONTOPREV',
  'Ticker': 'ODPV3',
  'CompanyName': 'ODONTOPREV S.A.'},
 {'Nome de Pregão': 'OI', 'Ticker': 'OIBR3', 'CompanyName': 'OI S.A.'},
 {'Nome de Pregão': 'ONCOCLINICAS',
  'Ticker': 'ONCO3',
  'CompanyName': 'ONCOCLINICAS DO BRASIL SERVICOS MEDICOS  S.A.'},
 {'Nome de Pregão': 'ORIZON',
  'Ticker': 'ORVR3',
  'CompanyName': 'ORIZON VALORIZACAO DE RESIDUOS S.A.'},
 {'Nome de Pregão': 'OSX BRASIL',
  'Ticker': 'OSXB3',
  'CompanyName': 'OSX BRASIL S.A.'},
 {'Nome de Pregão': 'OUROFINO S/A',
  'Ticker': 'OFSA3',
  'CompanyName': 'OURO FINO SAUDE ANIMAL PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'PADTEC',
  'Ticker': 'PDTC3',
  'CompanyName': 'PADTEC HOLDING S.A.'},
 {'Nome de Pregão': 'PANATLANTICA',
  'Ticker': 'PATI3',
  'CompanyName': 'PANATLANTICA S.A.'},
 {'Nome de Pregão': 'PARANAPANEMA',
  'Ticker': 'PMAM3',
  'CompanyName': 'PARANAPANEMA S.A.'},
 {'Nome de Pregão': 'PATRIMAR',
  'Ticker': 0,
  'CompanyName': 'PATRIMAR ENGENHARIA S.A.'},
 {'Nome de Pregão': 'PORTOBELLO', 'Ticker': 'PTBL3', 'CompanyName': 'PBG S/A'},
 {'Nome de Pregão': 'PDG REALT',
  'Ticker': 'PDGR3',
  'CompanyName': 'PDG REALTY S.A. EMPREEND E PARTICIPACOES'},
 {'Nome de Pregão': 'PETZ',
  'Ticker': 'PETZ3',
  'CompanyName': 'PET CENTER COMERCIO  E PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'PETROBRAS',
  'Ticker': 'PETR3',
  'CompanyName': 'PETROLEO BRASILEIRO S.A. PETROBRAS'},
 {'Nome de Pregão': 'PETRORECSA',
  'Ticker': 'RECV3',
  'CompanyName': 'PETRORECÔNCAVO S.A.'},
 {'Nome de Pregão': 'PETTENATI',
  'Ticker': 'PTNT3',
  'CompanyName': 'PETTENATI S.A. INDUSTRIA TEXTIL'},
 {'Nome de Pregão': 'PLANOEPLANO',
  'Ticker': 'PLPL3',
  'CompanyName': 'PLANO & PLANO DESENVOLVIMENTO IMOBILIÁRIO S.A.'},
 {'Nome de Pregão': 'PLASCAR PART',
  'Ticker': 'B3',
  'CompanyName': 'PLASCAR PARTICIPACOES INDUSTRIAIS S.A.'},
 {'Nome de Pregão': 'POLPAR', 'Ticker': 'PPAR3', 'CompanyName': 'POLPAR S.A.'},
 {'Nome de Pregão': 'POMIFRUTAS',
  'Ticker': 'FRTA3',
  'CompanyName': 'POMIFRUTAS S/A'},
 {'Nome de Pregão': 'PORTO SEGURO',
  'Ticker': 'PSSA3',
  'CompanyName': 'PORTO SEGURO S.A.'},
 {'Nome de Pregão': 'POSITIVO TEC',
  'Ticker': 'POSI3',
  'CompanyName': 'POSITIVO TECNOLOGIA S.A.'},
 {'Nome de Pregão': 'PRATICA',
  'Ticker': 'PTCA3',
  'CompanyName': 'PRATICA PRODUTOS S.A.'},
 {'Nome de Pregão': 'PRINER',
  'Ticker': 'PRNR3',
  'CompanyName': 'PRINER SERVIÇOS INDUSTRIAIS S.A.'},
 {'Nome de Pregão': 'PETRORIO', 'Ticker': 'PRIO3', 'CompanyName': 'PRIO S.A.'},
 {'Nome de Pregão': 'PROMAN',
  'Ticker': 'PRMN3B',
  'CompanyName': 'PRODUTORES ENERGET.DE MANSO S.A.- PROMAN'},
 {'Nome de Pregão': 'PROFARMA',
  'Ticker': 'PFRM3',
  'CompanyName': 'PROFARMA DISTRIB PROD FARMACEUTICOS S.A.'},
 {'Nome de Pregão': 'PROMPT PART',
  'Ticker': 'PRPT3B',
  'CompanyName': 'PROMPT PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'QUALICORP',
  'Ticker': 'QUAL3',
  'CompanyName': 'QUALICORP CONSULTORIA E CORRETORA DE SEGUROS S.A.'},
 {'Nome de Pregão': 'QUALITY SOFT',
  'Ticker': 'QUSW3',
  'CompanyName': 'QUALITY SOFTWARE S.A.'},
 {'Nome de Pregão': 'RAIADROGASIL',
  'Ticker': 'RADL3',
  'CompanyName': 'RAIA DROGASIL S.A.'},
 {'Nome de Pregão': 'RAIZEN', 'Ticker': 'RAIZ4', 'CompanyName': 'RAIZEN S.A.'},
 {'Nome de Pregão': 'RANDON PART',
  'Ticker': 'RAPT3',
  'CompanyName': 'RANDON S.A. IMPLEMENTOS E PARTICIPACOES'},
 {'Nome de Pregão': 'RECRUSUL',
  'Ticker': 'RCSL3',
  'CompanyName': 'RECRUSUL S.A.'},
 {'Nome de Pregão': 'REDE D OR',
  'Ticker': 'RDOR3',
  'CompanyName': 'REDE DOR SÃO LUIZ S.A.'},
 {'Nome de Pregão': 'REDE ENERGIA',
  'Ticker': 'REDE3',
  'CompanyName': 'REDE ENERGIA PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'PET MANGUINH',
  'Ticker': 'RPMG3',
  'CompanyName': 'REFINARIA DE PETROLEOS MANGUINHOS S.A.'},
 {'Nome de Pregão': 'RENOVA',
  'Ticker': 'RNEW3',
  'CompanyName': 'RENOVA ENERGIA S.A.'},
 {'Nome de Pregão': 'GER PARANAP',
  'Ticker': 'GEPA3',
  'CompanyName': 'RIO PARANAPANEMA ENERGIA S.A.'},
 {'Nome de Pregão': 'RNI',
  'Ticker': 'RDNI3',
  'CompanyName': 'RNI NEGÓCIOS IMOBILIÁRIOS S.A.'},
 {'Nome de Pregão': 'ROMI', 'Ticker': 'ROMI3', 'CompanyName': 'ROMI S.A.'},
 {'Nome de Pregão': 'ROSSI RESID',
  'Ticker': 'RSID3',
  'CompanyName': 'ROSSI RESIDENCIAL S.A.'},
 {'Nome de Pregão': 'RUMO S.A.',
  'Ticker': 'RAIL3',
  'CompanyName': 'RUMO S.A.'},
 {'Nome de Pregão': 'SANSUY',
  'Ticker': 'SNSY3',
  'CompanyName': 'SANSUY S.A. INDUSTRIA DE PLASTICOS'},
 {'Nome de Pregão': 'SANTOS BRP',
  'Ticker': 'STPB3',
  'CompanyName': 'SANTOS BRASIL PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'SAO CARLOS',
  'Ticker': 'SCAR3',
  'CompanyName': 'SAO CARLOS EMPREEND E PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'SAO MARTINHO',
  'Ticker': 'SMTO3',
  'CompanyName': 'SAO MARTINHO S.A.'},
 {'Nome de Pregão': 'SPTURIS',
  'Ticker': 'AHEB3',
  'CompanyName': 'SAO PAULO TURISMO S.A.'},
 {'Nome de Pregão': 'SCHULZ', 'Ticker': 'SHUL3', 'CompanyName': 'SCHULZ S.A.'},
 {'Nome de Pregão': 'ASSAI',
  'Ticker': 'ASAI3',
  'CompanyName': 'SENDAS DISTRIBUIDORA S.A.'},
 {'Nome de Pregão': 'SEQUOIA LOG',
  'Ticker': 'SEQL3',
  'CompanyName': 'SEQUOIA LOGISTICA E TRANSPORTES S.A'},
 {'Nome de Pregão': 'SER EDUCA',
  'Ticker': 'SEER3',
  'CompanyName': 'SER EDUCACIONAL S.A.'},
 {'Nome de Pregão': 'SERENA',
  'Ticker': 'SRNA3',
  'CompanyName': 'SERENA ENERGIA S.A.'},
 {'Nome de Pregão': 'ALIPERTI',
  'Ticker': 'APTI3',
  'CompanyName': 'SIDERURGICA J. L. ALIPERTI S.A.'},
 {'Nome de Pregão': 'SIMPAR', 'Ticker': 'SIMH3', 'CompanyName': 'SIMPAR S.A.'},
 {'Nome de Pregão': 'SLC AGRICOLA',
  'Ticker': 'SLCE3',
  'CompanyName': 'SLC AGRICOLA S.A.'},
 {'Nome de Pregão': 'SMART FIT',
  'Ticker': 'SMFT3',
  'CompanyName': 'SMARTFIT ESCOLA DE GINÁSTICA E DANÇA S.A.'},
 {'Nome de Pregão': 'SONDOTECNICA',
  'Ticker': 'SOND3',
  'CompanyName': 'SONDOTECNICA ENGENHARIA SOLOS S.A.'},
 {'Nome de Pregão': 'SPRINGS',
  'Ticker': 'SGPS3',
  'CompanyName': 'SPRINGS GLOBAL PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'STATKRAFT',
  'Ticker': 'STKF3',
  'CompanyName': 'STATKRAFT ENERGIAS RENOVAVEIS S.A.'},
 {'Nome de Pregão': 'SUDESTE S/A',
  'Ticker': 'OPSE3B',
  'CompanyName': 'SUDESTE S.A.'},
 {'Nome de Pregão': 'SUL 116 PART',
  'Ticker': 'OPTS3B',
  'CompanyName': 'SUL 116 PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'SUZANO HOLD',
  'Ticker': 'NEMO3',
  'CompanyName': 'SUZANO HOLDING S.A.'},
 {'Nome de Pregão': 'SUZANO S.A.',
  'Ticker': 'SUZB3',
  'CompanyName': 'SUZANO S.A.'},
 {'Nome de Pregão': 'SYN PROP TEC',
  'Ticker': 'SYNE3',
  'CompanyName': 'SYN PROP E TECH S.A.'},
 {'Nome de Pregão': 'TIME FOR FUN',
  'Ticker': 'SHOW3',
  'CompanyName': 'T4F ENTRETENIMENTO S.A.'},
 {'Nome de Pregão': 'TAURUS ARMAS',
  'Ticker': 'TASA3',
  'CompanyName': 'TAURUS ARMAS S.A.'},
 {'Nome de Pregão': 'TC', 'Ticker': 'TRAD3', 'CompanyName': 'TC S.A.'},
 {'Nome de Pregão': 'TECHNOS',
  'Ticker': 'TECN3',
  'CompanyName': 'TECHNOS S.A.'},
 {'Nome de Pregão': 'TECNISA',
  'Ticker': 'TCSA3',
  'CompanyName': 'TECNISA S.A.'},
 {'Nome de Pregão': 'TEGMA',
  'Ticker': 'tgma3',
  'CompanyName': 'TEGMA GESTAO LOGISTICA S.A.'},
 {'Nome de Pregão': 'TEGRA INCORP',
  'Ticker': 'TEGA',
  'CompanyName': 'TEGRA INCORPORADORA S.A.'},
 {'Nome de Pregão': 'TEKA',
  'Ticker': 'TEKA3',
  'CompanyName': 'TEKA-TECELAGEM KUEHNRICH S.A.'},
 {'Nome de Pregão': 'TEKNO',
  'Ticker': 'TKNO3',
  'CompanyName': 'TEKNO S.A. - INDUSTRIA E COMERCIO'},
 {'Nome de Pregão': 'TELEBRAS',
  'Ticker': 'TELB3',
  'CompanyName': 'TELEC BRASILEIRAS S.A. TELEBRAS'},
 {'Nome de Pregão': 'TELEF BRASIL',
  'Ticker': 'VIVT3',
  'CompanyName': 'TELEFÔNICA BRASIL S.A'},
 {'Nome de Pregão': 'MENEZES CORT',
  'Ticker': 0,
  'CompanyName': 'TERMINAL GARAGEM MENEZES CORTES S.A.'},
 {'Nome de Pregão': 'TERRASANTAPA',
  'Ticker': 'LAND3',
  'CompanyName': 'TERRA SANTA PROPRIEDADES AGRICOLAS S.A.'},
 {'Nome de Pregão': 'TEX RENAUX',
  'Ticker': 'TRXR3',
  'CompanyName': 'TEXTIL RENAUXVIEW S.A.'},
 {'Nome de Pregão': 'TIM', 'Ticker': 'TIMS3', 'CompanyName': 'TIM S.A.'},
 {'Nome de Pregão': 'TOTVS', 'Ticker': 'TOTS3', 'CompanyName': 'TOTVS S.A.'},
 {'Nome de Pregão': 'TRIUNFO PART',
  'Ticker': 'TPIS3',
  'CompanyName': 'TPI - TRIUNFO PARTICIP. E INVEST. S.A.'},
 {'Nome de Pregão': 'TRACK FIELD',
  'Ticker': 'TFCO4',
  'CompanyName': 'TRACK & FIELD CO S.A.'},
 {'Nome de Pregão': 'TAESA',
  'Ticker': 'TAEE3',
  'CompanyName': 'TRANSMISSORA ALIANÇA DE ENERGIA ELÉTRICA S.A.'},
 {'Nome de Pregão': '3TENTOS',
  'Ticker': 'TTEN3',
  'CompanyName': 'TRÊS TENTOS AGROINDUSTRIAL S/A'},
 {'Nome de Pregão': 'TREVISA',
  'Ticker': 8192,
  'CompanyName': 'TREVISA INVESTIMENTOS S.A.'},
 {'Nome de Pregão': 'TRIPLE PLAY',
  'Ticker': 0,
  'CompanyName': 'TRIPLE PLAY BRASIL PARTICIPAÇÕES S.A.'},
 {'Nome de Pregão': 'TRISUL', 'Ticker': 'TRIS3', 'CompanyName': 'TRISUL S.A.'},
 {'Nome de Pregão': 'CRISTAL',
  'Ticker': 'CRPG3',
  'CompanyName': 'TRONOX PIGMENTOS DO BRASIL S.A.'},
 {'Nome de Pregão': 'TUPY', 'Ticker': 'TUPY3', 'CompanyName': 'TUPY S.A.'},
 {'Nome de Pregão': 'ULTRAPAR',
  'Ticker': 'UGPA3',
  'CompanyName': 'ULTRAPAR PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'UNICASA',
  'Ticker': 'UCAS3',
  'CompanyName': 'UNICASA INDÚSTRIA DE MÓVEIS S.A.'},
 {'Nome de Pregão': 'UNIFIQUE',
  'Ticker': 'FIQE3',
  'CompanyName': 'UNIFIQUE TELECOMUNICAÇÕES S.A.'},
 {'Nome de Pregão': 'UNIPAR',
  'Ticker': 'UNIP3',
  'CompanyName': 'UNIPAR CARBOCLORO S.A.'},
 {'Nome de Pregão': 'UPTICK',
  'Ticker': 'UPKP3B',
  'CompanyName': 'UPTICK PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'USIMINAS',
  'Ticker': 'USIM3',
  'CompanyName': 'USINAS SID DE MINAS GERAIS S.A.-USIMINAS'},
 {'Nome de Pregão': 'VALE', 'Ticker': 'VALE3', 'CompanyName': 'VALE S.A.'},
 {'Nome de Pregão': 'VALID',
  'Ticker': 'VLID3',
  'CompanyName': 'VALID SOLUÇÕES S.A.'},
 {'Nome de Pregão': 'VAMOS',
  'Ticker': 'VAMO3',
  'CompanyName': 'VAMOS LOCAÇÃO DE CAMINHÕES. MÁQUINAS E EQUIP. S.A.'},
 {'Nome de Pregão': 'VESTE',
  'Ticker': 'VSTE3',
  'CompanyName': 'VESTE S.A. ESTILO'},
 {'Nome de Pregão': 'VIBRA',
  'Ticker': 'VBBR3',
  'CompanyName': 'VIBRA ENERGIA S.A.'},
 {'Nome de Pregão': 'VITTIA', 'Ticker': 'VITT3', 'CompanyName': 'VITTIA S.A.'},
 {'Nome de Pregão': 'VIVARA S.A.',
  'Ticker': 'VIVA3',
  'CompanyName': 'VIVARA PARTICIPAÇOES S.A'},
 {'Nome de Pregão': 'VIVER',
  'Ticker': 'VIVR3',
  'CompanyName': 'VIVER INCORPORADORA E CONSTRUTORA S.A.'},
 {'Nome de Pregão': 'VULCABRAS',
  'Ticker': 'VULC3',
  'CompanyName': 'VULCABRAS S.A.'},
 {'Nome de Pregão': 'WEG', 'Ticker': 'WEGE3', 'CompanyName': 'WEG S.A.'},
 {'Nome de Pregão': 'WESTWING',
  'Ticker': 'WEST3',
  'CompanyName': 'WESTWING COMERCIO VAREJISTA S.A.'},
 {'Nome de Pregão': 'WETZEL S/A',
  'Ticker': 'MWET3',
  'CompanyName': 'WETZEL S.A.'},
 {'Nome de Pregão': 'WHIRLPOOL',
  'Ticker': 'WHRL3',
  'CompanyName': 'WHIRLPOOL S.A.'},
 {'Nome de Pregão': 'WILSON SONS',
  'Ticker': 'PORT3',
  'CompanyName': 'WILSON SONS S.A.'},
 {'Nome de Pregão': 'WIZ CO',
  'Ticker': 'WIZC3',
  'CompanyName': 'WIZ CO PARTICIPAÇÕES E CORRETAGEM DE SEGUROS S.A.'},
 {'Nome de Pregão': 'WLM IND COM',
  'Ticker': 'WLMM3',
  'CompanyName': 'WLM PART. E COMÉRCIO DE MÁQUINAS E VEÍCULOS S.A.'},
 {'Nome de Pregão': 'YBYRA S/A',
  'Ticker': 'YBRA3',
  'CompanyName': 'YBYRÁ CAPITAL S.A.'},
 {'Nome de Pregão': 'YDUQS PART',
  'Ticker': 'YDUQ3',
  'CompanyName': 'YDUQS PARTICIPACOES S.A.'},
 {'Nome de Pregão': 'ZAMP S.A.',
  'Ticker': 'ZAMP3',
  'CompanyName': 'ZAMP S.A.'}]

# Função para buscar dados históricos de ações via yfinance
def buscar_dados_acoes(tickers_input, data_inicio_input, data_fim_input):
    data_inicio = datetime.strptime(data_inicio_input, "%d/%m/%Y").strftime("%Y-%m-%d")
    data_fim = datetime.strptime(data_fim_input, "%d/%m/%Y").strftime("%Y-%m-%d")
    data_fim_ajustada = (datetime.strptime(data_fim, "%Y-%m-%d") + timedelta(days=1)).strftime("%Y-%m-%d")
    
    tickers = [
        ticker.strip() + '.SA' if any(char.isdigit() for char in ticker.strip()) and not ticker.strip().endswith('.SA')
        else ticker.strip()
        for ticker in tickers_input.split(",")
    ]

    dados_acoes_dict = {}
    erros = []

    for ticker in tickers:
        try:
            dados = yf.download(ticker, start=data_inicio, end=data_fim_ajustada, auto_adjust=False)
            if not dados.empty:
                dados.reset_index(inplace=True)
                dados['Ticker'] = ticker
                dados['Date'] = dados['Date'].dt.strftime('%d/%m/%Y')
                dados_acoes_dict[ticker] = dados
            else:
                erros.append(f"Sem dados para o ticker {ticker}")
        except Exception as e:
            erros.append(f"Erro ao buscar dados para {ticker}: {e}")
    
    return dados_acoes_dict, erros

# Função para calcular volatilidade histórica e GARCH
def calcular_volatilidade(df):
    df = df.sort_values(by='Date', ascending=False).copy()
    volatilidade_historica = {}
    volatilidade_garch = {}
    
    periodos_dias = {1: 252, 2: 509, 3: 761, 4: 1000, 5: 1250, 6: 1500, 7: 1750, 8: 2000, 9: 2250, 10: 2500}
    
    for years, dias in periodos_dias.items():
        df_period = df.head(dias).copy()
        df_period['Retornos_Log'] = np.log(df_period['Close'] / df_period['Close'].shift(1))
        df_period = df_period.dropna()
        
        if df_period.empty or len(df_period) < 30:
            volatilidade_historica[years] = np.nan
            volatilidade_garch[years] = np.nan
            continue
        
        vol_anualizada_hist = df_period['Retornos_Log'].std(ddof=1) * np.sqrt(252)
        volatilidade_historica[years] = vol_anualizada_hist
        
        try:
            model = arch_model(df_period['Retornos_Log'] * 10, vol='Garch', p=1, q=1)
            garch_result = model.fit(disp='off')
            vol_diaria_media = garch_result.conditional_volatility.mean() / 10
            vol_anualizada_garch = vol_diaria_media * np.sqrt(252)
            volatilidade_garch[years] = vol_anualizada_garch
        except:
            volatilidade_garch[years] = np.nan
    
    df_volatilidade = pd.DataFrame({
        'Volatilidade Histórica': pd.Series(volatilidade_historica),
        'Volatilidade GARCH(1,1)': pd.Series(volatilidade_garch)
    })
    df_volatilidade.index.name = 'Período (Anos)'
    return df_volatilidade

# Interface do Streamlit
st.title('Consulta dados históricos de Ações, Dividendos e Volatilidade')

# Entrada do usuário
tickers_input = st.text_input("Digite os tickers separados por vírgula (ex: PETR4, VALE3, ^BVSP):")
data_inicio_input = st.text_input("Digite a data de início (dd/mm/aaaa):")
data_fim_input = st.text_input("Digite a data de fim (dd/mm/aaaa):")
buscar_dividendos = st.checkbox("Adicionar os dividendos no período")
buscar_volatilidade = st.checkbox("Calcular volatilidade histórica e GARCH")

# Botão para buscar dados
if st.button('Buscar Dados'):
    if tickers_input and data_inicio_input and data_fim_input:
        dados_acoes_dict, erros = buscar_dados_acoes(tickers_input, data_inicio_input, data_fim_input)
        
        for erro in erros:
            st.info(erro)
        
        if not dados_acoes_dict:
            st.info("Nenhum dado de ações encontrado para os tickers e período especificados.")
        else:
            st.write("### Dados de Ações por Ticker:")
            for ticker, df_acao in dados_acoes_dict.items():
                st.write(f"#### {ticker}")
                st.dataframe(df_acao)
                
                if buscar_volatilidade:
                    df_volatilidade = calcular_volatilidade(df_acao)
                    st.write(f"### Volatilidade de {ticker}")
                    st.dataframe(df_volatilidade)
        
        # Exportar para Excel
        # Nome do arquivo de saída
nome_arquivo = "dados_acoes_dividendos_volatilidade.xlsx"

with pd.ExcelWriter(nome_arquivo) as writer:
    # 1️⃣ Gravar dados de ações (cada ticker em uma aba)
    for ticker, df_acao in dados_acoes_dict.items():
        # sheet_name não pode ter mais de 31 caracteres no Excel
        sheet_name = f"Acoes_{ticker[:25]}"
        
        # 🚨 Corrigir possíveis MultiIndex ou colunas aninhadas
        df_acao = df_acao.reset_index(drop=True)
        df_acao.columns = [str(col) for col in df_acao.columns]  # Garantir colunas simples
        
        df_acao.to_excel(writer, sheet_name=sheet_name, index=False)

    # 2️⃣ Gravar dividendos, se disponíveis
    if buscar_dividendos and dados_dividendos_dict:
        for ticker, df_divid in dados_dividendos_dict.items():
            sheet_name = f"Div_{ticker[:25]}"
            df_divid.to_excel(writer, sheet_name=sheet_name, index=False)

    # 3️⃣ Gravar os cálculos de volatilidade por ticker
    if calcular_volatilidade and dados_volatilidade_dict:
        for ticker, df_volatilidade in dados_volatilidade_dict.items():
            sheet_name = f"Vol_{ticker[:25]}"
            df_volatilidade.to_excel(writer, sheet_name=sheet_name, index=False)

# Botão para baixar o Excel no Streamlit
with open(nome_arquivo, 'rb') as file:
    st.download_button(
        label="Baixar arquivo Excel",
        data=file,
        file_name=nome_arquivo
    )
